version: '3'
services:
  api:
    image: pythrick/dateflix-api:latest
    build: 
      context: .
      dockerfile: ./build/dateflix-api/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./cmd/dateflix-api/.env

  db:
    image: postgres:14.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./cmd/dateflix-api/.env
    ports:
      - 5432:5432

volumes:
  pgdata:
